# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 588b1a45c185156df46d02990787028ada84597b76b3e2492ed7fb36bba6e8b35b86e1d623d1cbd4e610660249e169bb8eee77f4b2df9c468f02b2e2395f2541

test:
  secret_key_base: 4c939a82f68e1b6023fa176883793db9e82bb13a775367ffd848152c385f39a2efb6444c376831acaa8d137bb36f5273266b93bbe71e0e13209ece0c705d20ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
